### ISSUE TITLE
Fails build on Node 4.2.2 and 4.2.1

### ISSUE THREAD

**Issue by vartana** [ChrisWren/grunt-node-inspector#35]
Full Log can be found at http://pastebin.com/raw.php?i=fQFzUg9d
command$: npm install grunt-node-inspector --save-dev

    > v8-debug@0.4.6 preinstall /Users/foobar/Dev/test/node_modules/.staging/v8-debug-b52178330d463fdcb40dcbf347b9164d
    >  

    > v8-debug@0.4.6 install /Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug
    > node-pre-gyp install --fallback-to-build

      CXX(target) Release/obj.target/debug/src/debug.o
    In file included from ../src/debug.cc:2:
    ../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                            ^
    ../../nan/nan.h:256:25: note: previous definition is here
    NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                            ^
    ../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
        , node::smalloc::FreeCallback callback
          ~~~~~~^
    ../../nan/nan.h:672:12: error: no matching function for call to 'New'
        return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
               ^~~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from
          'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    /Users/foobar/.node-gyp/4.2.2/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *')
          would lose const qualifier
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    /Users/foobar/.node-gyp/4.2.2/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were
          provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                           ^
    /Users/foobar/.node-gyp/4.2.2/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were
          provided
    NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                           ^
    In file included from ../src/debug.cc:2:
    ../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
        return node::Buffer::New(v8::Isolate::GetCurrent(), size);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no
          known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
    class Local {
          ^
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no
          known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
    class Local {
          ^
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
      V8_INLINE Local(Local<S> that)
                ^
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
          'v8::MaybeLocal<v8::Object>'
      V8_INLINE Local(S* that)
                ^
    In file included from ../src/debug.cc:2:
    ../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
        return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
               ~~~~~~~~~~~~~~^
    ../src/debug.cc:194:25: warning: ISO C++11 does not allow conversion from string literal to 'char *' [-Wwritable-strings]
              result_type = "";
                            ^
    In file included from ../src/debug.cc:2:
    In file included from ../../nan/nan.h:24:
    In file included from /Users/foobar/.node-gyp/4.2.2/include/node/node.h:42:
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type
          'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested
          here
        return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
               ^
    ../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/debug.cc:2:
    In file included from ../../nan/nan.h:24:
    In file included from /Users/foobar/.node-gyp/4.2.2/include/node/node.h:42:
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type
          'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
        return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
               ^
    ../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/debug.cc:2:
    In file included from ../../nan/nan.h:24:
    In file included from /Users/foobar/.node-gyp/4.2.2/include/node/node.h:42:
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type
          'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested
          here
        return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
               ^
    ../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/debug.cc:2:
    In file included from ../../nan/nan.h:24:
    In file included from /Users/foobar/.node-gyp/4.2.2/include/node/node.h:42:
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../../nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
        return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
               ^
    ../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    In file included from ../src/debug.cc:2:
    In file included from ../../nan/nan.h:24:
    In file included from /Users/foobar/.node-gyp/4.2.2/include/node/node.h:42:
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:221:5: error: assigning to 'v8::String *volatile' from incompatible type 'v8::Value *'
        TYPE_CHECK(T, S);
        ^~~~~~~~~~~~~~~~
    /Users/foobar/.node-gyp/4.2.2/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
        *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                        ^ ~~~~~~~~~~~~~~~~~~
    ../src/debug.cc:168:18: note: in instantiation of function template specialization 'v8::Local<v8::String>::Local<v8::Value>' requested here
              return NanEscapeScope(value->ToString());
                     ^
    ../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
    # define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                                 ^
    1 warning and 10 errors generated.
    make: *** [Release/obj.target/debug/src/debug.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Darwin 15.0.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64"
    gyp ERR! cwd /Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug
    gyp ERR! node -v v4.2.2
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    node-pre-gyp ERR! build error 
    node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)
    node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/foobar/Dev/test/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
    node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
    node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
    node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
    node-pre-gyp ERR! System Darwin 15.0.0
    node-pre-gyp ERR! command "/usr/local/bin/node" "/Users/foobar/Dev/test/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
    node-pre-gyp ERR! cwd /Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug
    node-pre-gyp ERR! node -v v4.2.2
    node-pre-gyp ERR! node-pre-gyp -v v0.6.15
    node-pre-gyp ERR! not ok 
    Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/foobar/Dev/test/node_modules/grunt-node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)

**Comment by pihomeserver** [comment]
Same here. No way to build it on Ubuntu with node 4.2.2 and node-gyp 3.1
```
../node_modules/nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/home/chris/kupiki/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.19.0-25-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/chris/kupiki/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.1.0
npm WARN optional dep failed, continuing bufferutil@1.1.0
```

**Comment by fiznool** [comment]
Sorry for the late reply.

Unfortunately I'm not seeing this issue (Ubuntu 15.10, node 4.2.2, npm 2.14.9).

Perhaps this is a caching issue, it may be trying to install an older version of node-inspector. Could you try running `npm cache clean` and then retrying installation?

FWIW, here is my output:

```
npm install grunt-node-inspector --save-dev
npm WARN peerDependencies The peer dependency grunt@^0.4.5 included from grunt-node-inspector will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
 
> v8-debug@0.5.4 preinstall /home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
>  

 
> v8-profiler@5.3.2 preinstall /home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
>  

npm WARN optional dep failed, continuing default-browser-id@1.0.2
 
> utf-8-validate@1.2.1 install /home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.2.1 install /home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws/node_modules/bufferutil/build'

> v8-profiler@5.3.2 install /home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.3.2/node-v46-linux-x64/profiler.node" is installed via remote

> v8-debug@0.5.4 install /home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/home/fiznool/Code/sandbox/grunt-node-inspector-build-test/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.5.4/node-v46-linux-x64/debug.node" is installed via remote
grunt@0.4.5 node_modules/grunt
├── eventemitter2@0.4.14
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── async@0.1.22
├── colors@0.6.2
├── getobject@0.1.0
├── lodash@0.9.2
├── rimraf@2.2.8
├── hooker@0.2.3
├── grunt-legacy-util@0.2.0
├── exit@0.1.2
├── coffee-script@1.3.3
├── iconv-lite@0.2.11
├── underscore.string@2.2.1
├── nopt@1.0.10 (abbrev@1.0.7)
├── grunt-legacy-log@0.1.2 (grunt-legacy-log-utils@0.1.1, lodash@2.4.2, underscore.string@2.3.3)
├── glob@3.1.21 (inherits@1.0.2, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.1, lru-cache@2.7.0)
├── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

grunt-node-inspector@0.4.1 node_modules/grunt-node-inspector
└── node-inspector@0.12.3 (path-is-absolute@1.0.0, async@0.9.2, semver@4.3.6, debug@2.2.0, serve-favicon@2.3.0, strong-data-uri@1.0.3, rc@1.1.5, which@1.2.0, glob@5.0.15, express@4.13.3, yargs@3.30.0, biased-opener@0.2.6, ws@0.8.0, v8-profiler@5.3.2, v8-debug@0.5.4)
```

**Comment by ivaylopivanov** [comment]
ubuntu 14.04
node 5.0.0

gst$ npm install grunt-node-inspector --save-dev
npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
npm WARN install Couldn't install optional dependency: Unsupported

> v8-debug@0.5.4 preinstall /home/ivo/gst/node_modules/.staging/v8-debug-7405e1f19947d49a4dead83a47b49c3f
>  


> v8-profiler@5.3.2 preinstall /home/ivo/gst/node_modules/.staging/v8-profiler-aaff01d04ca1822b56e7f2e77d9aaee7
>  

npm WARN prefer global node-inspector@0.12.3 should be installed with -g

> bufferutil@1.2.1 install /home/ivo/gst/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/ivo/gst/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
/home/ivo/gst/node_modules/.bin/touch: 1: /home/ivo/gst/node_modules/.bin/touch: Syntax error: "(" unexpected
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 2
make: Leaving directory `/home/ivo/gst/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ivo/gst/node_modules/bufferutil
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:bufferutil bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil Exit status 1

> utf-8-validate@1.2.1 install /home/ivo/gst/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/home/ivo/gst/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
/home/ivo/gst/node_modules/.bin/touch: 1: /home/ivo/gst/node_modules/.bin/touch: Syntax error: "(" unexpected
make: *** [Release/obj.target/validation/src/validation.o] Error 2
make: Leaving directory `/home/ivo/gst/node_modules/utf-8-validate/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ivo/gst/node_modules/utf-8-validate
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN install:utf-8-validate utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate Exit status 1

> v8-debug@0.5.4 install /home/ivo/gst/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

make: Entering directory `/home/ivo/gst/node_modules/v8-debug/build'
  CXX(target) Release/obj.target/debug/src/debug.o
/home/ivo/gst/node_modules/.bin/touch: 1: /home/ivo/gst/node_modules/.bin/touch: Syntax error: "(" unexpected
make: *** [Release/obj.target/debug/src/debug.o] Error 2
make: Leaving directory `/home/ivo/gst/node_modules/v8-debug/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.13.0-57-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/ivo/gst/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/ivo/gst/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64"
gyp ERR! cwd /home/ivo/gst/node_modules/v8-debug
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ivo/gst/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node --module_name=debug --module_path=/home/ivo/gst/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ivo/gst/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.13.0-57-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/home/ivo/gst/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/ivo/gst/node_modules/v8-debug
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.17
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/ivo/gst/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64/debug.node --module_name=debug --module_path=/home/ivo/gst/node_modules/v8-debug/build/debug/v0.5.4/node-v47-linux-x64' (1)

**Comment by ivaylopivanov** [comment]
However, there's no problem if i do the following:

1. rm -rf node_modules
2. npm install node-inspector
3. npm instlall grunt
4. npm install grunt-node-inspector

**Comment by fiznool** [comment]
This is for node v5? If so please could you open a new issue, as this one
is tracking problems with v4.

**Comment by ivaylopivanov** [comment]
Done.

**Comment by golendukhin** [comment]
Have the same problem on Ubuntu 14.04:
node v5.6.0
npm v3.6.0
node-pre-gyp v0.6.21

**Comment by fiznool** [comment]
Closing this issue due to no further activity. If you are seeing this issue, please first try the resolution in #36 before commenting here - thanks!
